import { ProviderCapabilities, ProviderName, PROVIDERS } from '@/types';

export const PROVIDER_CAPABILITIES_MATRIX: Record<ProviderName | string, ProviderCapabilities> = {
  [PROVIDERS.OMDB]: {
    supportsSearch: true,
    supportsRefresh: true,
    supportsImages: true,
    supportsCredentials: true,
    canSearch: true,
    canFetchMetadata: true,
    canRefresh: true,
    hasPosterImages: true,
    requiresAuthKey: true,
  },
  [PROVIDERS.OPENLIBRARY]: {
    supportsSearch: true,
    supportsRefresh: true,
    supportsImages: true,
    supportsCredentials: false,
    canSearch: true,
    canFetchMetadata: true,
    canRefresh: true,
    hasPosterImages: true,
    requiresAuthKey: false,
  },
  [PROVIDERS.GOOGLE_BOOKS]: {
    supportsSearch: true,
    supportsRefresh: true,
    supportsImages: true,
    supportsCredentials: false,
    canSearch: true,
    canFetchMetadata: true,
    canRefresh: true,
    hasPosterImages: true,
    requiresAuthKey: false,
  },
  [PROVIDERS.TMDB]: {
    supportsSearch: true,
    supportsRefresh: true,
    supportsImages: true,
    supportsCredentials: true,
    canSearch: true,
    canFetchMetadata: true,
    canRefresh: true,
    hasPosterImages: true,
    requiresAuthKey: true,
  },
  github: {
    supportsSearch: true,
    supportsRefresh: true,
    supportsImages: false,
    supportsCredentials: false,
    canSearch: true,
    canFetchMetadata: true,
    canRefresh: true,
    hasPosterImages: false,
    requiresAuthKey: false,
  },
  website: {
    supportsSearch: false,
    supportsRefresh: true,
    supportsImages: true,
    supportsCredentials: false,
    canSearch: false,
    canFetchMetadata: true,
    canRefresh: true,
    hasPosterImages: true,
    requiresAuthKey: false,
  },
  [PROVIDERS.MANUAL]: {
    supportsSearch: false,
    supportsRefresh: false,
    supportsImages: false,
    supportsCredentials: false,
    canSearch: false,
    canFetchMetadata: false,
    canRefresh: false,
    hasPosterImages: false,
    requiresAuthKey: false,
  },
};

export function getProviderCapabilities(providerName: ProviderName | string): ProviderCapabilities {
  return PROVIDER_CAPABILITIES_MATRIX[providerName] || {
    supportsSearch: false,
    supportsRefresh: false,
    supportsImages: false,
    supportsCredentials: false,
    canSearch: false,
    canFetchMetadata: false,
    canRefresh: false,
    hasPosterImages: false,
    requiresAuthKey: false,
  };
}
